function [opts] = pdsolver_opts()

    dummy_cb = @(it, x, y) disp('');
    
    opts = struct('backend', 'pdhg', 'max_iters', 5000, 'cb_iters', 10, ...
                  'tol_primal', 1.0, 'tol_dual', 1.0, 'adapt_type', 'none', 'ads_gamma', 0, ...
                  'adb_alpha0', 0.5, 'adb_nu', 0.95, 'adb_delta', 1.5, 'adb_s', 10, 'precond', 'off', ...
                  'precond_alpha', 1, 'verbose', true, 'callback', ...
                  dummy_cb, 'bt_enabled', 0, 'bt_beta', 0.95, ...
                  'bt_gamma', 0.75, 'adc_delta', 1.05, 'adc_tau', 0.8);

end
