function [prob] = pdsolver_problem()

    prob = struct('', 'pdhg', 'max_iters', 5000, 'cb_iters', 10, ...
                  'tol_primal', 1.0, 'tol_dual', 1.0, 'adapt_type', 'none', 'ads_gamma', 0, ...
                  'adb_alpha0', 0.5, 'adb_nu', 0.95, 'adb_delta', 1.5, 'adb_s', 1, 'precond', 'off', ...
                  'precond_alpha', 1, 'verbose', false, 'callback', ...
                  dummy_cb, 'bt_enabled', 0, 'bt_beta', 0.95, ...
                  'bt_gamma', 0.75, 'adc_delta', 1.05, 'adc_tau', ...
                  0.8, 'sigma0', 1, 'tau0', 1);

end
