function [opts] = pdsolver_opts()

    dummy_cb = @(it, x, y) disp('');
    
    opts = struct('backend', 'pdhg', 'max_iters', 5000, 'cb_iters', 10, ...
                  'tolerance', 10.0, 'pdhg_type', 'alg1', 'gamma', 0, ...
                  'alpha0', 0.5, 'nu', 0.95, 'delta', 1.5, 's', 10, 'precond', 'off', ...
                  'precond_alpha', 1, 'verbose', true, 'callback', ...
                  dummy_cb, 'bt_beta', 0.95, 'bt_gamma', 0.75);

end
