cuda_lib = '/work/sdks/cudacurrent/lib64';
cuda_inc = '/work/sdks/cudacurrent/include';

if ismac
    cuda_lib = '/usr/local/cuda/lib';
    cuda_inc = '/usr/local/cuda/include';
end

unix('make -C ../build/ -j8');

if ismac
    eval(sprintf(['mex -g -largeArrayDims -output pdsolver ' ...
                  'CXXFLAGS=''\\$CXXFLAGS -stdlib=libstdc++'' '...
                  'LDFLAGS=''\\$LDFLAGS -stdlib=libstdc++ -Wl,-rpath,%s'' '...
                  'mex_pdsolver.cpp mex_factory.cpp ../build/libpdsolver.a' ...
                  ' -L%s -I%s -lcudart -lcublas -lcusparse -I../include' ], ...
                 cuda_lib, cuda_lib, cuda_inc))

    eval(sprintf(['mex -g -largeArrayDims -output pdsolver_eval_prox ' ...
                  'CXXFLAGS=''\\$CXXFLAGS -stdlib=libstdc++'' '...
                  'LDFLAGS=''\\$LDFLAGS -stdlib=libstdc++ -Wl,-rpath,%s'' '...
                  'mex_eval_prox.cpp mex_factory.cpp ../build/libpdsolver.a' ...
                  ' -L%s -I%s -lcudart -lcublas -lcusparse -I../include' ], ...
                 cuda_lib, cuda_lib, cuda_inc))

    eval(sprintf(['mex -g -largeArrayDims -output pdsolver_eval_linop ' ...
                  'CXXFLAGS=''\\$CXXFLAGS -stdlib=libstdc++'' '...
                  'LDFLAGS=''\\$LDFLAGS -stdlib=libstdc++ -Wl,-rpath,%s'' '...
                  'mex_eval_linop.cpp mex_factory.cpp ../build/libpdsolver.a' ...
                  ' -L%s -I%s -lcudart -lcublas -lcusparse -I../include' ], ...
                 cuda_lib, cuda_lib, cuda_inc))
else
%     eval(sprintf(['mex -g -largeArrayDims -output pdsolver ' ...
%                   'CXXFLAGS=''\\$CXXFLAGS'' '...
%                   'LDFLAGS=''\\$LDFLAGS -Wl,-rpath,%s'' '...
%                   'mex_pdsolver.cpp mex_factory.cpp ../build/libpdsolver.a' ...
%                   ' -L%s -I%s -lcudart -lcublas -lcusparse -I../include' ], ...
%                   cuda_lib, cuda_lib, cuda_inc))

    eval(sprintf(['mex -g -largeArrayDims -output pdsolver_eval_prox ' ...
                  'CXXFLAGS=''\\ -std=c++11'' '...
                  'LDFLAGS=''\\$LDFLAGS -Wl,-rpath,%s'' '...
                  'mex/mex_eval_prox.cu mex/mex_factory.cpp ../build/' ...
                  'libpdsolver.a' ...
                  ' -L%s -I%s -lcudart -lcublas -lcusparse -I../include' ], ...
                 cuda_lib, cuda_lib, cuda_inc))

%     eval(sprintf(['mex -g -largeArrayDims -output pdsolver_eval_linop ' ...
%                   'CXXFLAGS=''\\$CXXFLAGS'' '...
%                   'LDFLAGS=''\\$LDFLAGS -Wl,-rpath,%s'' '...
%                   'mex_eval_linop.cpp mex_factory.cpp ../build/' ...
%                   'libpdsolver.a' ...
%                   ' -L%s -I%s -lcudart -lcublas -lcusparse -I../include' ], ...
%                  cuda_lib, cuda_lib, cuda_inc))
end
