function run_all_tests()

    prost.init();
    
    unit_tests = { 
        'linop_dense'; ...
        'linop_dense_kron_id'; ...
        'linop_diags'; ...
        'linop_gradient2d'; ...
        'linop_gradient3d'; ...
        'linop_id_kron_dense'; ...
        'linop_id_kron_sparse'; ...
        'linop_sparse_zero'; ...
        'linop_sparse_kron_id'; ...
        'prox_conjugate'; ...
        'prox_conj_trans'; ...
        'prox_sum_ind_simplex'; ...
        'prox_sum_norm2'; ...
        'prox_transform'; ...
        'prox_sum_ind_psd_cone'; ...
                 };

    num_passed = 0;
    for i=1:size(unit_tests,1)
        fprintf('Running unit test "%s"...', unit_tests{i});
        passed = eval(['prost.test.test_', unit_tests{i}]);
        
        if passed
            fprintf(' success!\n');
            num_passed = num_passed + 1;
        end
    end

    fprintf('%d/%d unit tests passed.\n', ...
            num_passed, size(unit_tests, 1));
    
    prost.release();

end
