cuda_lib = '/usr/local/cuda/lib';
cuda_inc = '/usr/local/cuda/include';

unix('make -C ../../build/');

eval(sprintf(['mex -largeArrayDims -output pdsolver ' ...
                  'CXXFLAGS=''\\$CXXFLAGS -O3 -stdlib=libstdc++ -std=c++11'' '...
                  'LDFLAGS=''\\$LDFLAGS -stdlib=libstdc++ -Wl,-rpath,%s'' '...
                  'pdsolver_mex.cpp prox_create.cpp ../../build/libpdsolver.a' ...
                  ' -L%s -I%s -lcudart -lcublas -lcusparse' ], ...
                 cuda_lib, cuda_lib, cuda_inc))
             